apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: danxy1234/expiration
          env:
            - name: CLUSTER_ID
              value: ticketing
            - name: NATS_URL
              value: http://nats-clusterip-service:4222
            - name: REDIS_HOST
              value: expiration-redis-service
            - name: CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
