name: tests
on:
  pull_request:
    branches:
      - develop
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && yarn install --production && yarn test:ci
