name: tests-tickets
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && yarn && yarn test:ci
